name: Albert's Rollback test

on:
  pull_request:
    branches: ["main"]

  workflow_dispatch:
    inputs:
      rollback-file:
        description: the file to rollback
        required: true

jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
      - run: echo "filename: ${{ github.event_name.inputs.rollback-file }} ${{ github.event_name }}"
        # shell: bash
