name: Albert's Publish 

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: echo secret script
        run: echo ${{ secrets.ALBERT_SEC1 }}
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          registry-url: 'https://npm.pkg.github.com'
      - name: Bump version tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_release_rules: nb:patch,albert:major,fuck:minor
          # dry_run: true

      - name: Update package version
        uses: reedyuk/npm-version@1.1.1
        with:
          version: ${{ steps.tag_version.outputs.new_version }}
      # - run: npm publish
      #   working-directory: ./npkg/
      #   env: 
      #     NODE_AUTH_TOKEN: ${{ secrets.ALBERT_SEC1 }}
